spring.application.name=EmployeeManagement

spring.datasource.url=jdbc:mysql://nozomi.proxy.rlwy.net:17324/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=uuHaBcfWVQXIdEDDsJNOsVUXTwpiECTg

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
